FIND_PACKAGE(Teuchos REQUIRED
    CONFIG
    HINTS
      ${TPL_Teuchos_DIR}/lib/cmake/Teuchos
      ${TPL_Teuchos_DIR}
    COMPONENTS
      ${${PACKAGE_NAME}_Teuchos_REQUIRED_COMPONENTS}
    OPTIONAL_COMPONENTS
      ${${PACKAGE_NAME}_Teuchos_OPTIONAL_COMPONENTS}
)
GLOBAL_SET(TPL_Teuchos_INCLUDE_DIRS "${Teuchos_INCLUDE_DIRS};${Teuchos_LIBRARY_DIRS}")
GLOBAL_SET(TPL_Teuchos_LIBRARIES    "${Teuchos_LIBRARIES};${Teuchos_TPL_LIBRARIES}")
GLOBAL_SET(TPL_Teuchos_LIBRARY_DIRS "${Teuchos_LIBRARY_DIRS};${Teuchos_TPL_LIBRARY_DIRS}")
