FIND_PACKAGE(Tpetra REQUIRED
    CONFIG
    HINTS
      ${TPL_Tpetra_DIR}/lib/cmake/Tpetra
      ${TPL_Tpetra_DIR}
    COMPONENTS
      ${${PACKAGE_NAME}_Tpetra_REQUIRED_COMPONENTS}
    OPTIONAL_COMPONENTS
      ${${PACKAGE_NAME}_Tpetra_OPTIONAL_COMPONENTS}
)
GLOBAL_SET(TPL_Tpetra_INCLUDE_DIRS "${Tpetra_INCLUDE_DIRS};${Tpetra_LIBRARY_DIRS}")
GLOBAL_SET(TPL_Tpetra_LIBRARIES    "${Tpetra_LIBRARIES};${Tpetra_TPL_LIBRARIES}")
GLOBAL_SET(TPL_Tpetra_LIBRARY_DIRS "${Tpetra_LIBRARY_DIRS};${Tpetra_TPL_LIBRARY_DIRS}")
