FIND_PACKAGE(Kokkos REQUIRED
    CONFIG
    HINTS
      ${TPL_Kokkos_DIR}/lib/cmake/Kokkos
      ${TPL_Kokkos_DIR}
    COMPONENTS
      ${${PACKAGE_NAME}_Kokkos_REQUIRED_COMPONENTS}
    OPTIONAL_COMPONENTS
      ${${PACKAGE_NAME}_Kokkos_OPTIONAL_COMPONENTS}
)
GLOBAL_SET(TPL_Kokkos_INCLUDE_DIRS "${Kokkos_INCLUDE_DIRS};${Kokkos_LIBRARY_DIRS}")
GLOBAL_SET(TPL_Kokkos_LIBRARIES    "${Kokkos_LIBRARIES};${Kokkos_TPL_LIBRARIES}")
GLOBAL_SET(TPL_Kokkos_LIBRARY_DIRS "${Kokkos_LIBRARY_DIRS};${Kokkos_TPL_LIBRARY_DIRS}")
