FIND_PACKAGE(Belos REQUIRED
    CONFIG
    HINTS
      ${TPL_Belos_DIR}/lib/cmake/Belos
      ${TPL_Belos_DIR}
    COMPONENTS
      ${${PACKAGE_NAME}_Belos_REQUIRED_COMPONENTS}
    OPTIONAL_COMPONENTS
      ${${PACKAGE_NAME}_Belos_OPTIONAL_COMPONENTS}
)
GLOBAL_SET(TPL_Belos_INCLUDE_DIRS "${Belos_INCLUDE_DIRS};${Belos_LIBRARY_DIRS}")
GLOBAL_SET(TPL_Belos_LIBRARIES    "${Belos_LIBRARIES};${Belos_TPL_LIBRARIES}")
GLOBAL_SET(TPL_Belos_LIBRARY_DIRS "${Belos_LIBRARY_DIRS};${Belos_TPL_LIBRARY_DIRS}")
