FIND_PACKAGE(STK REQUIRED
    CONFIG
    HINTS
      ${TPL_STK_DIR}/lib/cmake/STK
      ${TPL_STK_DIR}
    COMPONENTS
      ${${PACKAGE_NAME}_STK_REQUIRED_COMPONENTS}
    OPTIONAL_COMPONENTS
      ${${PACKAGE_NAME}_STK_OPTIONAL_COMPONENTS}
)
GLOBAL_SET(TPL_STK_INCLUDE_DIRS "${STK_INCLUDE_DIRS};${STK_LIBRARY_DIRS}")
GLOBAL_SET(TPL_STK_LIBRARIES    "${STK_LIBRARIES};${STK_TPL_LIBRARIES}")
GLOBAL_SET(TPL_STK_LIBRARY_DIRS "${STK_LIBRARY_DIRS};${STK_TPL_LIBRARY_DIRS}")
