TRILINOS_ROOT_DIR=$1
MUNDY_SOURCE_DIR=$2

echo "Using Trilinos dir: $TRILINOS_ROOT_DIR"
echo "Using STK test-app dir: $MUNDY_SOURCE_DIR"

cmake \
-DCMAKE_BUILD_TYPE=${BUILD_TYPE:-DEBUG} \
-DCMAKE_CXX_COMPILER=mpicxx \
-DCMAKE_CXX_FLAGS="-O0 -g -march=native" \
-DENABLE_OPENMP=${ENABLE_OPENMP:-ON} \
-DENABLE_CUDA=${ENABLE_CUDA:-OFF} \
-DKokkos_ENABLE_SERIAL=ON \
-DKokkos_ENABLE_OPENMP=OFF \
-DKokkos_ENABLE_CUDA=OFF \
-DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS:-OFF} \
-DTPL_Kokkos_DIR:PATH=${TRILINOS_ROOT_DIR} \
-DTPL_STK_DIR:PATH=${TRILINOS_ROOT_DIR} \
-DTPL_Teuchos_DIR:PATH=${TRILINOS_ROOT_DIR} \
${ccache_args} \
${compiler_flags} \
${install_dir} \
${extra_args} \
${MUNDY_SOURCE_DIR}
