mundy:  
  globals:
    count: 4
    attribute_0:
      name: TIME_STEP_SIZE
      type: double # This is how we know how to serialize and deserialize the attribute
      value: 0.01
    attribute_1:
      name: TIME
      type: double
      value: 0.0
    attribute_2:
      name: NUM_STEPS
      type: int
      value: 1000
    attribute_3:
      name: SKIN_DISTANCE
      type: double
      value: 1.0

  methods:
    ##! \name Setup
    ##@{
    write_mesh:
      instance_of: MESH_WRITER
      fixed_params:
        io_fields:
          count: 2
          field_0:
            name: NODE_FORCE
            output_format: vector3
          field_1:
            name: NODE_VELOCITY
            output_format: vector3
        io_part_names: [SPHEROCYLINDER_SEGMENTS]
        io_global_names: [TIME_STEP_SIZE, TIME, SKIN_DISTANCE]

    zero_out_transient_fields:
      instance_of: FILL_FIELDS
      fixed_params:
        field_names: [NODE_FORCE, NODE_VELOCITY]
        field_values: [0.0, 0.0]  
    ##@}

    ##! \name Hertzian contact
    ##@{
    segment_compute_aabb:
      instance_of: COMPUTE_AABB
      fixed_params:
        enabled_kernel_names: [SPHEROCYLINDER_SEGMENT]
        element_aabb_field_name: ELEMENT_AABB
        buffer_distance_attribute_name: SKIN_DISTANCE
        input_selector: "LOCALLY_OWNED & SPHEROCYLINDER_SEGMENTS"

    generate_segment_neighbor_linkers:
      instance_of: GENERATE_NEIGHBOR_LINKERS
      fixed_params:
        enabled_technique_name: STK_SEARCH
        source_selector: "LOCALLY_OWNED & SPHEROCYLINDER_SEGMENTS"
        target_selector: "LOCALLY_OWNED & SPHEROCYLINDER_SEGMENTS"
        linker_part_name: SPHEROCYLINDER_SEGMENT_SPHEROCYLINDER_SEGMENT_LINKERS

    compute_ssd_and_cn:
      instance_of: COMPUTE_SIGNED_SEPARATION_DISTANCE_AND_CONTACT_NORMAL
      fixed_params:
        enabled_kernel_names: [
            SPHEROCYLINDER_SEGMENT_SPHEROCYLINDER_SEGMENT_LINKER
          ]
        input_selector: "LOCALLY_OWNED & SPHEROCYLINDER_SEGMENT_SPHEROCYLINDER_SEGMENT_LINKER"

    evaluate_linker_potentials:
      instance_of: EVALUATE_LINKER_POTENTIALS
      params:
        enabled_kernel_names: [
            SPHEROCYLINDER_SEGMENT_SPHEROCYLINDER_SEGMENT_HERTZIAN_CONTACT
          ]
        input_selector: "LOCALLY_OWNED & SPHEROCYLINDER_SEGMENT_SPHEROCYLINDER_SEGMENT_LINKER"

    linker_potential_force_reduction:
      instance_of: LINKER_POTENTIAL_FORCE_REDUCTION
      fixed_params:
        enabled_kernel_names: [SPHEROCYLINDER_SEGMENT]

    destroy_neighbor_linkers:
      instance_of: DESTROY_NEIGHBOR_LINKERS
      fixed_params:
        enabled_technique_name: DESTROY_DISTANT_NEIGHBORS

    
    ##@}

    ##! \name Time integration
    ##@{
    time_integrator:
      instance_of: COMPUTE_TIME_INTEGRATION
      fixed_params:
        enabled_technique_name: VELOCITY_VERLET
        force_block: [
            evaluate_linker_potentials, 
            linker_potential_force_reduction
        ]


    ##@}

    


