tribits_package_define_dependencies(
  LIB_REQUIRED_PACKAGES
  LIB_OPTIONAL_PACKAGES
  TEST_REQUIRED_PACKAGES
  TEST_OPTIONAL_PACKAGES
  LIB_REQUIRED_TPLS Kokkos fmt
  LIB_OPTIONAL_TPLS Teuchos
  TEST_REQUIRED_TPLS GTest
  TEST_OPTIONAL_TPLS
  )
