tribits_package_define_dependencies(
  LIB_REQUIRED_PACKAGES MundyCore MundyMath MundyMesh MundyMeta MundyAgents MundyShapes
  LIB_OPTIONAL_PACKAGES
  TEST_REQUIRED_PACKAGES
  TEST_OPTIONAL_PACKAGES
  LIB_REQUIRED_TPLS STK Kokkos Teuchos fmt
  LIB_OPTIONAL_TPLS MPI ArborX CUDA
  TEST_REQUIRED_TPLS GTest
  TEST_OPTIONAL_TPLS
  )