tribits_package_define_dependencies(
  LIB_REQUIRED_PACKAGES MundyCore MundyMesh MundyMeta MundyShape MundyConstraint
  LIB_OPTIONAL_PACKAGES 
  TEST_REQUIRED_PACKAGES
  TEST_OPTIONAL_PACKAGES
  LIB_REQUIRED_TPLS STK Teuchos
  LIB_OPTIONAL_TPLS
  TEST_REQUIRED_TPLS GTest
  TEST_OPTIONAL_TPLS MPI
  )