tribits_package_define_dependencies(
  LIB_REQUIRED_PACKAGES MundyCore MundyMesh MundyMeta
  LIB_OPTIONAL_PACKAGES MundyShape MundyConstraint
  TEST_REQUIRED_PACKAGES
  TEST_OPTIONAL_PACKAGES
  LIB_REQUIRED_TPLS STK Teuchos
  LIB_OPTIONAL_TPLS
  TEST_REQUIRED_TPLS gtest
  TEST_OPTIONAL_TPLS
  )