tribits_package_define_dependencies(
  LIB_REQUIRED_PACKAGES MundyCore MundyMesh MundyMeta MundyAgent
  LIB_OPTIONAL_PACKAGES MundyShape
  TEST_REQUIRED_PACKAGES
  TEST_OPTIONAL_PACKAGES
  LIB_REQUIRED_TPLS STK Teuchos
  LIB_OPTIONAL_TPLS MPI ArborX
  TEST_REQUIRED_TPLS GTest
  TEST_OPTIONAL_TPLS
  )